# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_auto_20180305_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
    ]
